### ISSUE TITLE
Bug: constructer behaves weirdly for science0

### ISSUE THREAD

**Issue by WilliamRoyNelson** [gcottrell13/idlefactorygame#2]
When I assigned a constructer[sic] to science0, it displays 
`Constructor (Infinity/s): 1 (Infinity/s)`
It does consume resources rapidly, but it doesn't actually seem to produce science0

science1 seems to work correctly.
![image](https://github.com/gcottrell13/idlefactorygame/assets/7910938/c0f921ec-3907-4826-bf00-1f38f6f322aa)

**Comment by gcottrell13** [comment]
oh I set its craft time to 0. oops

**Comment by gcottrell13** [comment]
fixed in v1.1
